### ISSUE TITLE
Link outdated

### ISSUE THREAD

**Issue by Jonas-Ste** [computational-psychiatry-course/precourse-preparation#1]
The link to the Calculus 1 ressource from Ohio State University seems to be outdated.
Based on my research I think they just moved away from coursera and now developed their own MOOC platform.
This is the correct link I think:
https://ximera.osu.edu/mooculus/calculus1

**Comment by inezpereira** [comment]
Hi! Thanks for contributing to the list :) 
Can you explain why you think the resource is outdated? The content is still on Coursera, the links and videos are working and I see no warning on the website that this resource should not be used (and the content is awesome!).
The link you sent has a lot of content but no videos. Hence parsing it might be more difficult compared to the Coursera video format, especially for beginners, which is the target group.

**Comment by Jonas-Ste** [comment]
Hi!
Thank you even more for creating this comprehensive list! :)
At least for me the link to Calculus 1 by OHU (https://www.coursera.org/learn/calculus1) creates error 404. I tried it using different browsers. Might be an issue because of accessing from a German IP? But also tried an American one via VPN with no effect. 
Is the link really working for you? Then this problem certainly is on my end and I apologize and will try to figure it out myself... and looking forward to use the your list to prepare for CPC :)

**Comment by inezpereira** [comment]
Oh, you are right! It works for me because I enrolled ages ago and still have access, but opening the link on a private window yields a 404 error. I will try to find out if they have a video version of this course elsewhere! 
Otherwise, Khan Academy is also a great resource.
Thank you for pointing this out to us!

**Comment by Jonas-Ste** [comment]
That's interesting that it's still available for you because you enrolled previously! Thank you very much for taking the effort to search for a video version of the course somewhere else - I will in the meantime enjoy the Khan Academy course and all the other useful CPC resources.
